### ISSUE TITLE
how can i build envirment in centos 7.

### ISSUE THREAD

**Issue by anzhaozhong** [everitoken/evt#131]
[ 64%] Built target rocksdb
[ 64%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/uint128.cpp.o
In file included from /root/evt/evt/libraries/fc/include/fc/uint128.hpp:6:0,
                 from /root/evt/evt/libraries/fc/src/uint128.cpp:1:
/root/evt/evt/libraries/fc/include/fc/exception/exception.hpp:8:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
make[3]: *** [libraries/fc/CMakeFiles/fc.dir/src/uint128.cpp.o] Error 1
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
make[1]: *** [programs/evtd/CMakeFiles/evtd.dir/rule] Error 2
make: *** [evtd] Error 2

**Comment by harrywong** [comment]
It's not recommended to build on CentOS now. Because evt is required to be built by GCC 8. But there's no official GCC 8 repo now. It always recommend to use Docker and we have rich documents and help script.

-
Harry

________________________________
发件人: anzhaozhong <notifications@github.com>
发送时间: 星期四, 二月 21, 2019 10:20
收件人: everitoken/evt
抄送: Subscribed
主题: [everitoken/evt] how can i build envirment in centos 7. (#131)


[ 64%] Built target rocksdb
[ 64%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/uint128.cpp.o
In file included from /root/evt/evt/libraries/fc/include/fc/uint128.hpp:6:0,
from /root/evt/evt/libraries/fc/src/uint128.cpp:1:
/root/evt/evt/libraries/fc/include/fc/exception/exception.hpp:8:20: fatal error: optional: No such file or directory
#include
^
compilation terminated.
make[3]: *** [libraries/fc/CMakeFiles/fc.dir/src/uint128.cpp.o] Error 1
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
make[1]: *** [programs/evtd/CMakeFiles/evtd.dir/rule] Error 2
make: *** [evtd] Error 2

―

**Comment by anzhaozhong** [comment]
thks, i tried docker firstly. but i meeted a trouble too...
how can i mount docker volume on appoint path by docker_ops.py

**Comment by harrywong** [comment]
You want to mount data to physical path on host instead of using volume?

-
Harry

________________________________
发件人: anzhaozhong <notifications@github.com>
发送时间: 星期四, 二月 21, 2019 10:39
收件人: everitoken/evt
抄送: Harry; Comment
主题: Re: [everitoken/evt] how can i build envirment in centos 7. (#131)


thks, i tried docker firstly. but i meeted a trouble too...
how can i mount docker volume on appoint path by docker_ops.py

―

**Comment by anzhaozhong** [comment]
> You want to mount data to physical path on host instead of using volume? - Harry
> […](#)
> ________________________________ 发件人: anzhaozhong <notifications@github.com> 发送时间: 星期四, 二月 21, 2019 10:39 收件人: everitoken/evt 抄送: Harry; Comment 主题: Re: [everitoken/evt] how can i build envirment in centos 7. (#131) thks, i tried docker firstly. but i meeted a trouble too... how can i mount docker volume on appoint path by docker_ops.py ― You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feveritoken%2Fevt%2Fissues%2F131%23issuecomment-465838851&data=02%7C01%7C%7C6e23a84ec00543cf121a08d697a5bf6f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636863135461622789&sdata=gofzM5XGQdC5QMJRe9mQjLPG8PzuhIhGOMLacqRHLSA%3D&reserved=0>, or mute the thread<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZs3-r4lWHD-3Tim1PCzzt8Y44a88Rnks5vPgbIgaJpZM4bGgoZ&data=02%7C01%7C%7C6e23a84ec00543cf121a08d697a5bf6f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636863135461632800&sdata=wILt%2BqnyaTtgjp2eHqHOjsYKRlxL9UuGwV2Yw5Y11n8%3D&reserved=0>.

yes, i want mount data to /mnt/evt/data, because volume path is at /var/lib/docker/...

**Comment by harrywong** [comment]
Sure. I'll add that support in docker_ops.py tomorrow.

-
Harry

________________________________
发件人: anzhaozhong <notifications@github.com>
发送时间: 星期四, 二月 21, 2019 10:51
收件人: everitoken/evt
抄送: Harry; Comment
主题: Re: [everitoken/evt] how can i build envirment in centos 7. (#131)


You want to mount data to physical path on host instead of using volume? - Harry
…
________________________________ 发件人: anzhaozhong notifications@github.com<mailto:notifications@github.com> 发送时间: 星期四, 二月 21, 2019 10:39 收件人: everitoken/evt 抄送: Harry; Comment 主题: Re: [everitoken/evt] how can i build envirment in centos 7. (#131<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feveritoken%2Fevt%2Fissues%2F131&data=02%7C01%7C%7Cf11c8b3267f6468ca54608d697a76f8e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636863142714569209&sdata=p5T0Z6dCcMgIYF3cjqyZG30NvP%2BnPrp0VZeLfvCbBBA%3D&reserved=0>) thks, i tried docker firstly. but i meeted a trouble too... how can i mount docker volume on appoint path by docker_ops.py D You are receiving this because you commented. Reply to this email directly, view it on GitHubhttps://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feveritoken%2Fevt%2Fissues%2F131%23issuecomment-465838851&data=02%7C01%7C%7C6e23a84ec00543cf121a08d697a5bf6f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636863135461622789&sdata=gofzM5XGQdC5QMJRe9mQjLPG8PzuhIhGOMLacqRHLSA%3D&reserved=0<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feveritoken%2Fevt%2Fissues%2F131%23issuecomment-465838851&data=02%7C01%7C%7Cf11c8b3267f6468ca54608d697a76f8e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636863142714579217&sdata=5gGs3uBeFpUHYVhdlrJidpYTegdPGt0atQ6ZyKWjTuQ%3D&reserved=0>, or mute the threadhttps://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZs3-r4lWHD-3Tim1PCzzt8Y44a88Rnks5vPgbIgaJpZM4bGgoZ&data=02%7C01%7C%7C6e23a84ec00543cf121a08d697a5bf6f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636863135461632800&sdata=wILt%2BqnyaTtgjp2eHqHOjsYKRlxL9UuGwV2Yw5Y11n8%3D&reserved=0<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZs3-r4lWHD-3Tim1PCzzt8Y44a88Rnks5vPgbIgaJpZM4bGgoZ&data=02%7C01%7C%7Cf11c8b3267f6468ca54608d697a76f8e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636863142714579217&sdata=FE2%2BahjSY1cddF0haRUEBG8rU9hkAUa34Fc4P2skEJQ%3D&reserved=0>.

yes, i want mount data to /mnt/evt/data, because volume path is at /var/lib/docker/...

―

**Comment by harrywong** [comment]
Hi, I've updated the docker_ops.py to support specifying a host path instead of data volume when creating evtd or postgres.

**Comment by anzhaozhong** [comment]
> u

thks ^.^. And i have solved the problem by add options(-graph -exec-root) to dockerd.

**Comment by harrywong** [comment]
Yeah that's another option. :)

-
Harry

________________________________
发件人: anzhaozhong <notifications@github.com>
发送时间: 星期二, 二月 26, 2019 10:52
收件人: everitoken/evt
抄送: Harry; Comment
主题: Re: [everitoken/evt] how can i build envirment in centos 7. (#131)


u

thks ^.^. And i have solved the problem by add options(-graph -exec-root) to dockerd.

―
